# Generated by Django 5.2.4 on 2025-08-11 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('voting_round', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-voting_round'],
                'unique_together': {('table_name', 'voting_round')},
            },
        ),
        migrations.CreateModel(
            name='VotingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_nickname', models.CharField(max_length=100)),
                ('vote_value', models.IntegerField()),
                ('voting_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='poker.votinghistory')),
            ],
            options={
                'unique_together': {('voting_history', 'player_nickname')},
            },
        ),
    ]
